// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AcousticDbContext))]
    [Migration("20240625205242_seedDooctor")]
    partial class seedDooctor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentTime = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7961),
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7963),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AppointmentTime = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7971),
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7972),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AppointmentTime = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7976),
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7977),
                            DoctorId = 3,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AppointmentTime = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7980),
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(7981),
                            DoctorId = 4,
                            IsDeleted = false,
                            PatientId = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorSpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorSpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Biography = "Id 3 olan Doktor Özgeçmiş Example",
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7856),
                            DoctorSpecializationId = 1,
                            Experience = 10
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Kalp Doktoru Özgeçmiş Example",
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7862),
                            DoctorSpecializationId = 2,
                            Experience = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.DoctorInterest", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("DoctorInterests");

                    b.HasData(
                        new
                        {
                            DoctorId = 3,
                            InterestId = 1
                        },
                        new
                        {
                            DoctorId = 3,
                            InterestId = 2
                        },
                        new
                        {
                            DoctorId = 4,
                            InterestId = 7
                        },
                        new
                        {
                            DoctorId = 4,
                            InterestId = 8
                        });
                });

            modelBuilder.Entity("Domain.Entities.DoctorSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DoctorSpecializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6523),
                            NameEN = "Neurosurgery",
                            NameTR = "Beyin ve Sinir Cerrahisi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6535),
                            NameEN = "Dermatology",
                            NameTR = "Dermatoloji"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6536),
                            NameEN = "General Surgery",
                            NameTR = "Genel Cerrahi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6537),
                            NameEN = "Ophthalmology",
                            NameTR = "Göz Hastalıkları"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6538),
                            NameEN = "Internal Medicine",
                            NameTR = "İç Hastalıkları"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6540),
                            NameEN = "Obstetrics and Gynecology",
                            NameTR = "Kadın Hastalıkları ve Doğum"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6541),
                            NameEN = "Otorhinolaryngology",
                            NameTR = "Kulak Burun Boğaz"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6542),
                            NameEN = "Orthopedics and Traumatology",
                            NameTR = "Ortopedi ve Travmatoloji"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6543),
                            NameEN = "Urology",
                            NameTR = "Üroloji"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6545),
                            NameEN = "Pediatrics",
                            NameTR = "Çocuk Sağlığı ve Hastalıkları"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8089),
                            Name = "Kardiyoloji Araştırmaları"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8097),
                            Name = "Çocuk Sağlığı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8101),
                            Name = "Onkoloji Tedavi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8105),
                            Name = "Nöroloji ve Beyin Cerrahisi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8108),
                            Name = "Endokrinoloji ve Metabolizma"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8113),
                            Name = "Gastroenteroloji ve Sindirim Sistemi"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8117),
                            Name = "Psikiyatri ve Mental Sağlık"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8120),
                            Name = "Aile Hekimliği ve Birinci Basamak Sağlık Hizmetleri"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8123),
                            Name = "Parkinson Hastalığı"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8128),
                            Name = "Bunama"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6769),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6779),
                            Name = "Appointment.Delete"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6783),
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Main St",
                            AppointmentId = 0,
                            BloodType = "A+",
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7740)
                        },
                        new
                        {
                            Id = 2,
                            Address = "1233 Main St",
                            AppointmentId = 0,
                            BloodType = "B+",
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7750)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExaminationFindings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8506),
                            Diagnosis = " Hipertansiyon",
                            ExaminationFindings = "Yüksek kan basıncı"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8514),
                            Diagnosis = " Hipertansiyon",
                            ExaminationFindings = "Yüksek kan basıncı"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8518),
                            Diagnosis = "Diabetes Mellitus",
                            ExaminationFindings = "Fasting blood sugar level of 140 mg/dL"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(8522),
                            Diagnosis = "Chronic Obstructive Pulmonary Disease (COPD)",
                            ExaminationFindings = "Reduced lung function on spirometry"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7420),
                            Email = "hasta1@example.com",
                            FirstName = "John",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234567890",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7431),
                            Email = "hasta2@example.com",
                            FirstName = "Jonathan",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Corwin",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234512345",
                            UserType = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7436),
                            Email = "doktor1@example.com",
                            FirstName = "batu",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "cerrahlar",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234512312",
                            UserType = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7440),
                            Email = "doktor4@example.com",
                            FirstName = "Fatma",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Koç",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500004",
                            UserType = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7442),
                            Email = "doktor5@example.com",
                            FirstName = "Mehmet",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Öz",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500005",
                            UserType = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7444),
                            Email = "doktor6@example.com",
                            FirstName = "Canan",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Çelik",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500006",
                            UserType = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7446),
                            Email = "doktor7@example.com",
                            FirstName = "Emre",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Arı",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500007",
                            UserType = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7448),
                            Email = "doktor8@example.com",
                            FirstName = "Burak",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Temiz",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500008",
                            UserType = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7450),
                            Email = "doktor9@example.com",
                            FirstName = "Seda",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Ak",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500009",
                            UserType = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7452),
                            Email = "doktor10@example.com",
                            FirstName = "Murat",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Tez",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500010",
                            UserType = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7454),
                            Email = "doktor11@example.com",
                            FirstName = "Zeynep",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Bal",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500011",
                            UserType = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7456),
                            Email = "doktor12@example.com",
                            FirstName = "Kemal",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Sağ",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500012",
                            UserType = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7555),
                            Email = "doktor13@example.com",
                            FirstName = "Cansu",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Dur",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500013",
                            UserType = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7557),
                            Email = "doktor14@example.com",
                            FirstName = "Oğuz",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Kurt",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500014",
                            UserType = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7559),
                            Email = "doktor15@example.com",
                            FirstName = "Esra",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Deniz",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500015",
                            UserType = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7561),
                            Email = "doktor16@example.com",
                            FirstName = "Baran",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Gül",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500016",
                            UserType = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7563),
                            Email = "doktor17@example.com",
                            FirstName = "Duygu",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Aydın",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500017",
                            UserType = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7565),
                            Email = "doktor18@example.com",
                            FirstName = "Tarkan",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Kara",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500018",
                            UserType = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7567),
                            Email = "doktor19@example.com",
                            FirstName = "Nil",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Koç",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500019",
                            UserType = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7569),
                            Email = "doktor20@example.com",
                            FirstName = "Sami",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Öztürk",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500020",
                            UserType = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7570),
                            Email = "doktor21@example.com",
                            FirstName = "Ece",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Uzun",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500021",
                            UserType = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7572),
                            Email = "doktor22@example.com",
                            FirstName = "Levent",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Yıldız",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500022",
                            UserType = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7574),
                            Email = "doktor23@example.com",
                            FirstName = "Selin",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Demirci",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500023",
                            UserType = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7576),
                            Email = "doktor24@example.com",
                            FirstName = "Onur",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Akar",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500024",
                            UserType = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7578),
                            Email = "doktor25@example.com",
                            FirstName = "İrem",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Dere",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500025",
                            UserType = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7580),
                            Email = "doktor26@example.com",
                            FirstName = "Cenk",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Taş",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500026",
                            UserType = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7582),
                            Email = "doktor27@example.com",
                            FirstName = "Hande",
                            Gender = "Female",
                            IsDeleted = false,
                            LastName = "Yener",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234500027",
                            UserType = 1
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2024, 6, 25, 20, 52, 41, 778, DateTimeKind.Utc).AddTicks(7604),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            Gender = "Male",
                            IsDeleted = false,
                            LastName = "Yöneticioğlu",
                            PasswordHash = new byte[] { 176, 123, 144, 99, 96, 232, 186, 120, 49, 147, 82, 51, 70, 227, 167, 199, 186, 190, 222, 148, 60, 243, 79, 196, 25, 157, 133, 6, 74, 57, 147, 189, 49, 21, 158, 135, 242, 125, 37, 169, 242, 187, 32, 36, 121, 126, 72, 155, 201, 64, 39, 106, 11, 100, 97, 147, 65, 245, 142, 245, 215, 156, 208, 55 },
                            PasswordSalt = new byte[] { 170, 233, 97, 66, 35, 173, 217, 139, 74, 241, 132, 181, 36, 193, 63, 164, 156, 161, 216, 232, 201, 180, 134, 55, 161, 127, 123, 29, 192, 15, 185, 11, 168, 208, 47, 28, 62, 40, 197, 131, 254, 208, 49, 101, 39, 70, 140, 159, 135, 118, 123, 181, 191, 191, 228, 106, 46, 243, 23, 220, 7, 99, 21, 236, 153, 109, 192, 100, 117, 17, 12, 161, 38, 200, 37, 66, 75, 240, 207, 184, 204, 113, 187, 190, 139, 65, 184, 10, 240, 142, 88, 0, 222, 31, 24, 56, 251, 208, 131, 39, 186, 55, 251, 222, 199, 172, 25, 69, 26, 33, 201, 239, 141, 5, 55, 61, 190, 93, 0, 210, 180, 79, 204, 49, 213, 82, 77, 37 },
                            PhoneNumber = "1234512345",
                            UserType = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6891),
                            OperationClaimId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6900),
                            OperationClaimId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6904),
                            OperationClaimId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 25, 23, 52, 41, 778, DateTimeKind.Local).AddTicks(6908),
                            OperationClaimId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointment")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "Patient")
                        .WithMany("Appointment")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Domain.Entities.DoctorSpecialization", "DoctorSpecialization")
                        .WithMany()
                        .HasForeignKey("DoctorSpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Domain.Entities.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorSpecialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DoctorInterest", b =>
                {
                    b.HasOne("Domain.Entities.Doctor", "Doctor")
                        .WithMany("DoctorInterest")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Interest", "Interest")
                        .WithMany("DoctorInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Domain.Entities.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Domain.Entities.Appointment", "Appointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.HasOne("Domain.Entities.Appointment", "Appointment")
                        .WithOne("Report")
                        .HasForeignKey("Domain.Entities.Report", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Domain.Entities.UserOperationClaim", b =>
                {
                    b.HasOne("Domain.Entities.OperationClaim", "OperationClaim")
                        .WithMany("UserOperationClaims")
                        .HasForeignKey("OperationClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationClaim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Prescriptions");

                    b.Navigation("Report")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointment");

                    b.Navigation("DoctorInterest");
                });

            modelBuilder.Entity("Domain.Entities.Interest", b =>
                {
                    b.Navigation("DoctorInterests");
                });

            modelBuilder.Entity("Domain.Entities.OperationClaim", b =>
                {
                    b.Navigation("UserOperationClaims");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
